CREATE TABLE IF NOT EXISTS roles (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    department TEXT NOT NULL DEFAULT '',
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role_id INTEGER NOT NULL REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS priorities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sla_hours INTEGER
);

CREATE TABLE IF NOT EXISTS statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ticket_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP NULL,
    short_description TEXT NOT NULL,
    detailed_description TEXT NOT NULL DEFAULT '',
    priority_id INTEGER NOT NULL REFERENCES priorities(id),
    type_id INTEGER NOT NULL REFERENCES ticket_types(id),
    status_id INTEGER NOT NULL REFERENCES statuses(id),
    author_id INTEGER NOT NULL REFERENCES users(id),
    assignee_id INTEGER NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS ticket_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    changed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    changed_by INTEGER NOT NULL REFERENCES users(id),
    field_name TEXT NOT NULL,
    old_value TEXT NULL,
    new_value TEXT NULL
);

INSERT INTO roles (id, name, description)
VALUES
    (1, 'Сотрудник', 'Создает и отслеживает свои заявки'),
    (2, 'Исполнитель', 'Берет и выполняет назначенные заявки'),
    (3, 'Диспетчер', 'Назначает исполнителей и ведет очередь'),
    (4, 'Администратор', 'Управляет ролями и справочниками')
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

INSERT INTO priorities (name, sla_hours)
VALUES
    ('Низкий', 72),
    ('Средний', 24),
    ('Высокий', 8)
ON CONFLICT (name) DO NOTHING;

INSERT INTO statuses (name, description)
VALUES
    ('Новая', 'Заявка только что создана'),
    ('В работе', 'Исполнитель взял задачу'),
    ('Выполнена', 'Работа завершена'),
    ('Отменена', 'Заявка отменена')
ON CONFLICT (name) DO NOTHING;

INSERT INTO ticket_types (name)
VALUES
    ('Инцидент'),
    ('Запрос'),
    ('Доступ')
ON CONFLICT (name) DO NOTHING;

INSERT INTO users (last_name, first_name, middle_name, email, phone, department, login, password_hash, role_id)
VALUES
    ('Админов', 'Алексей', '', 'admin@akbars.local', '+7 900 000-00-01', 'ИТ', 'admin', 'admin123', 4),
    ('Диспетчерова', 'Дарья', '', 'dispatcher@akbars.local', '+7 900 000-00-02', 'Service Desk', 'dispatcher', 'dispatcher123', 3),
    ('Исполнителев', 'Иван', '', 'executor@akbars.local', '+7 900 000-00-03', 'Поддержка', 'executor', 'executor123', 2),
    ('Сотрудников', 'Павел', '', 'employee@akbars.local', '+7 900 000-00-04', 'Бухгалтерия', 'employee', 'employee123', 1)
ON CONFLICT (login) DO NOTHING;

DO $$
DECLARE
    employee_user_id INTEGER;
    dispatcher_user_id INTEGER;
    executor_user_id INTEGER;
    low_priority_id INTEGER;
    medium_priority_id INTEGER;
    status_new_id INTEGER;
    status_progress_id INTEGER;
    incident_type_id INTEGER;
BEGIN
    SELECT id INTO employee_user_id FROM users WHERE login = 'employee';
    SELECT id INTO dispatcher_user_id FROM users WHERE login = 'dispatcher';
    SELECT id INTO executor_user_id FROM users WHERE login = 'executor';
    SELECT id INTO low_priority_id FROM priorities WHERE name = 'Низкий';
    SELECT id INTO medium_priority_id FROM priorities WHERE name = 'Средний';
    SELECT id INTO status_new_id FROM statuses WHERE name = 'Новая';
    SELECT id INTO status_progress_id FROM statuses WHERE name = 'В работе';
    SELECT id INTO incident_type_id FROM ticket_types WHERE name = 'Инцидент';

    IF NOT EXISTS (SELECT 1 FROM tickets) THEN
        INSERT INTO tickets (
            short_description,
            detailed_description,
            priority_id,
            type_id,
            status_id,
            author_id,
            assignee_id
        )
        VALUES
            (
                'Не работает печать в бухгалтерии',
                'После обновления драйвера принтер перестал отвечать.',
                medium_priority_id,
                incident_type_id,
                status_new_id,
                employee_user_id,
                NULL
            ),
            (
                'Нужно выдать доступ к общей папке',
                'Запрос на доступ для нового сотрудника отдела.',
                low_priority_id,
                incident_type_id,
                status_progress_id,
                employee_user_id,
                executor_user_id
            );

        INSERT INTO ticket_history (ticket_id, changed_by, field_name, old_value, new_value)
        SELECT id, dispatcher_user_id, 'status', 'Новая', 'В работе'
        FROM tickets
        WHERE assignee_id = executor_user_id;
    END IF;
END $$;
